# Generated by Django 2.1.1 on 2018-09-24 20:05

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Message',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.CharField(help_text='Enter a type of message you would like to see a total of (e.g. symbol clear)', max_length=200)),
            ],
        ),
    ]
